config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  namespace :admin do
    resources :users, only:[:index, :show, :edit, :update]
    resources :posts, only:[:index, :show, :destroy]
    resources :tags, only:[:index, :create, :edit, :update]
    resources :prefectures, only:[:index, :create, :edit, :update]
    resources :comments, only:[:index, :show, :destroy]
  end

  scope module: :public do
    root to: "homes#top"
    resources :users, only:[:index, :show, :edit, :update] do
      member do
        get :favorites
      end
      resource :relationships, only:[:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :posts, only:[:new, :create, :index, :show, :edit, :update, :destroy] do
      get :search, on: :collection
      resource :favorites, only:[:create, :destroy]
      resources :comments, only:[:create, :destroy]
    end
    resources :tags, only:[:index, :show]
    resources :prefectures, only:[:index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :comment, presence: true

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def index
    @comments = Comment.page(params[:page]).per(10)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_comments_path
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-9 offset-2">
      <div class="customer-login-form">
        <div class="my-2">
          <h4>コメント一覧</h4>
          <table class='table table-inverse'>
            <thead>
              <tr>
                <th>コメント</th>
                <th>投稿</th>
                <th>コメントユーザー</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @comments.each do |comment| %>
              <tr>
                <td><%= comment.comment %></td>
                <td>
                  <%= link_to admin_post_path(comment.post) do %>
                    <%= image_tag comment.post.get_image(100,100) %>
                  <% end %>
                </td>
                <td>
                  <%= link_to admin_user_path(comment.user) do %>
                    <%= image_tag comment.user.get_profile_image(50,50) %>
                  <% end %>
                </td>
                <td>
                  <%= link_to 'Destroy', admin_comment_path(comment.id), method: :delete, class: "btn btn-sm btn-danger" %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <%= paginate @comments %>
        </div>
      </div>
    </div>
  </div>
</div>