config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  namespace :admin do
    resources :users, only:[:index, :show, :edit, :update]
    resources :posts, only:[:index, :show, :destroy]
    resources :tags, only:[:index, :create, :edit, :update]
    resources :prefectures, only:[:index, :create, :edit, :update]
    resources :comments, only:[:index, :show, :destroy]
  end

  scope module: :public do
    root to: "homes#top"
    resources :users, only:[:index, :show, :edit, :update] do
      member do
        get :favorites
      end
      resource :relationships, only:[:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :posts, only:[:new, :create, :index, :show, :edit, :update, :destroy] do
      get :search, on: :collection
      resource :favorites, only:[:create, :destroy]
      resources :comments, only:[:create, :destroy]
    end
    resources :tags, only:[:index, :show]
    resources :prefectures, only:[:index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord

  has_many :posts, dependent: :destroy

  validates :name, presence: true

end

app/controllers/admin/prefectures_controller.rb
class Admin::PrefecturesController < ApplicationController

  before_action :authenticate_admin!

  def index
    @prefecture = Prefecture.new
    @prefectures = Prefecture.page(params[:page]).per(10)
  end

  def create
    @prefecture = Prefecture.new(prefecture_params)
    if @prefecture.save
      redirect_to request.referer
    else
      @prefectures = Prefecture.all
      render :index
    end
  end

  def edit
    @prefecture = Prefecture.find(params[:id])
  end

  def update
    @prefecture = Prefecture.find(params[:id])
    if @prefecture.update(prefecture_params)
      redirect_to admin_prefectures_path
    else
      render :edit
    end
  end

  private
    def prefecture_params
      params.require(:prefecture).permit(:name)
    end
end

app/helpers/admin/prefectures_helper.rb
module Admin::PrefecturesHelper
end

app/views/admin/prefectures/_form.html.erb
<%= f.label :name, "都道府県名" %>
<%= f.text_field :name, placeholder: "都道府県名", class: "col-6 ml-3 my-3 login-form-style" %>

app/views/admin/prefectures/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-9 offset-2">
      <div class="customer-login-form">
        <h4>都道府県編集</h4>
        <%= form_with model: @prefecture, url: admin_prefecture_path(@prefecture.id) do |f| %>
          <%= render 'form', f: f %>
          <div class="d-flex flex-row-reverse my-3">
            <%= f.submit "変更を保存", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/prefectures/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-9 offset-2">
      <div class="customer-login-form">
        <div class="my-2">
          <h4>都道府県一覧・追加</h4>
          <%= form_with model: @prefecture, url: admin_prefectures_path do |f| %>
            <%= render 'form', f: f %>
            <div class="d-flex flex-row-reverse my-3">
              <%= f.submit "新規登録", class: "btn btn-success" %>
            </div>
          <% end %>
        </div>

        <table class="table">
          <thead>
            <tr>
              <th>都道府県</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @prefectures.each do |prefecture| %>
              <tr>
                <td><%= prefecture.name %></td>
                <td>
                  <div class="d-flex flex-row-reverse">
                    <%= link_to "編集する", edit_admin_prefecture_path(prefecture.id), class: "btn btn-success"%>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @prefectures %>
     </div>
    </div>
  </div>
</div>